# https://github.com/mborne/docker-devbox/blob/master/minio/flysystem-bundle.md
services:
    # s3_client:
    #     class: 'AsyncAws\S3\S3Client'
    #     arguments:
    #         - endpoint: "%env(S3_ENDPOINT)%"
    #           accessKeyId: "%env(S3_ACCESS_KEY)%"
    #           accessKeySecret: "%env(S3_SECRET_KEY)%"
    #           region: "sbg"
    #           pathStyleEndpoint: true # s3_url/bucket_name/objet_path
    #           sendChunkedBody: true

    simple_s3_client:
        class: 'AsyncAws\SimpleS3\SimpleS3Client'
        arguments:
            - endpoint: "%env(S3_ENDPOINT)%"
              accessKeyId: "%env(S3_ACCESS_KEY)%"
              accessKeySecret: "%env(S3_SECRET_KEY)%"
              region: "sbg"
              pathStyleEndpoint: true # s3_url/bucket_name/objet_path
              sendChunkedBody: true

# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        s3.storage:
            adapter: "asyncaws"
            options:
                client: "simple_s3_client"
                bucket: "%env(S3_BUCKET_NAME)%"
