when@dev:
    nelmio_api_doc:
        documentation:
            info:
                title: API interne de cartes.gouv.fr
                description: >
                    Documentation auto-générée des routes internes du site [cartes.gouv.fr](%env(resolve:APP_ROOT_URL)%) qui s'appuie sur [l'API Entrepôt](%api_entrepot_url%/swagger-ui/index.html) et [l'API Collaborative](%api_espaceco_url%/doc).


                    Pour tester les routes à travers le swagger, vous devez être connecté sur le site. Ensuite, en cliquant sur le bouton "Authorize", vous devez renseigner le champ `X-Requested-With` avec la valeur exacte `XMLHttpRequest` pour que l'API interne accepte la requête.
                    Attention : le "Try it out" ne fonctionne pas forcément sur toutes les routes car certaines sont mal documentées.
                # version: 1.0.0

            components:
                securitySchemes:
                    XMLHttpRequest:
                        type: apiKey
                        in: header
                        name: X-Requested-With
                        description: >
                            Saisir la valeur exacte : `XMLHttpRequest`
            security:
                - XMLHttpRequest:

        areas: # to filter documented areas
            path_patterns:
                - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
