twig:
    default_path: "%kernel.project_dir%/templates"
    globals:
        api_espaceco_url: "%api_espaceco_url%"
        catalogue_url: "%catalogue_url%"
        config: "%config%"
        annexes_url: "%annexes_url%"

when@test:
    twig:
        strict_variables: true
