version: "3.4"

networks:
    cartesgouvfr_network:

services:
    app:
        image: ignf/cartes.gouv.fr:latest
        build:
            context: .
            dockerfile: .docker/Dockerfile
            target: prod
            args:
                - HTTP_PROXY
                - HTTPS_PROXY
        env_file:
            - .env.local
        environment:
            - HTTP_PROXY=${HTTP_PROXY}
            - HTTPS_PROXY=${HTTPS_PROXY}
            - http_proxy=${HTTP_PROXY}
            - https_proxy=${HTTPS_PROXY}
        ports:
            - "9090:8000"
        networks:
            - cartesgouvfr_network
        restart: unless-stopped
