version: "3.4"

networks:
    web_dev:
        external: true

services:
    app_dev:
        image: ignf/cartes.gouv.fr:dev
        build:
            context: .
            dockerfile: .docker/Dockerfile
            target: dev
            args:
                - HTTP_PROXY
                - HTTPS_PROXY
        env_file:
            - .env.local
        environment:
            - HTTP_PROXY=${HTTP_PROXY}
            - HTTPS_PROXY=${HTTPS_PROXY}
            - http_proxy=${HTTP_PROXY}
            - https_proxy=${HTTPS_PROXY}
        working_dir: /opt/cartesgouvfr-site
        volumes:
            - .:/opt/cartesgouvfr-site
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - "9092:8000"
        networks:
            - web_dev
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.cartesgouvfr.rule=Host(`cartesgouvfr-dev.docker.localhost`)"
            - "traefik.http.routers.cartesgouvfr.entrypoints=websecure"
            - "traefik.http.services.cartesgouvfr.loadbalancer.server.port=8000"
