/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PrivateEspaceCollaboratifRouteRouteImport } from './routes/_private/espace-collaboratif/route'
import { Route as PrivateMesDocumentsRouteImport } from './routes/_private/mes-documents'
import { Route as PrivateMesPermissionsRouteImport } from './routes/_private/mes-permissions'
import { Route as PrivateMonCompteRouteImport } from './routes/_private/mon-compte'
import { Route as PrivateRejoindreDesCommunautesRouteImport } from './routes/_private/rejoindre-des-communautes'
import { Route as Public404RouteImport } from './routes/_public/404'
import { Route as PublicConnexionDesactiveeRouteImport } from './routes/_public/connexion-desactivee'
import { Route as PublicPublierUneDonneeRouteImport } from './routes/_public/publier-une-donnee'
import { Route as PrivateConfigurationAlertesRouteImport } from './routes/_private/configuration/alertes'
import { Route as PrivateDemandeAccesFileIdentifierRouteImport } from './routes/_private/demande-acces.$fileIdentifier'
import { Route as PrivateEspaceCollaboratifIndexRouteImport } from './routes/_private/espace-collaboratif/index'
import { Route as PrivateMesClesIndexRouteImport } from './routes/_private/mes-cles/index'
import { Route as PrivateMesClesAjoutRouteImport } from './routes/_private/mes-cles/ajout'
import { Route as PrivateTableauDeBordIndexRouteImport } from './routes/_private/tableau-de-bord/index'
import { Route as PrivateTableauDeBordStatistiquesDeConsommationRouteImport } from './routes/_private/tableau-de-bord/statistiques-de-consommation'
import { Route as PrivateEspaceCollaboratifCommunityIdCreerUnGuichetRouteImport } from './routes/_private/espace-collaboratif/$communityId.creer-un-guichet'
import { Route as PrivateEspaceCollaboratifCommunityIdGererLeGuichetRouteImport } from './routes/_private/espace-collaboratif/$communityId.gerer-le-guichet'
import { Route as PrivateEspaceCollaboratifCommunityIdInvitationRouteImport } from './routes/_private/espace-collaboratif/$communityId.invitation'
import { Route as PrivateMesClesKeyIdModificationRouteImport } from './routes/_private/mes-cles/$keyId.modification'
import { Route as PrivateTableauDeBordCommunauteCommunityIdRouteRouteImport } from './routes/_private/tableau-de-bord/communaute/$communityId/route'
import { Route as PrivateTableauDeBordEntrepotsIndexRouteImport } from './routes/_private/tableau-de-bord/entrepots/index'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdRouteRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/route'
import { Route as PrivateTableauDeBordEntrepotsDemandeDeCreationRouteImport } from './routes/_private/tableau-de-bord/entrepots/demande-de-creation'
import { Route as PrivateTableauDeBordCommunauteCommunityIdIndexRouteImport } from './routes/_private/tableau-de-bord/communaute/$communityId/index'
import { Route as PrivateTableauDeBordCommunauteCommunityIdMembresRouteImport } from './routes/_private/tableau-de-bord/communaute/$communityId/membres'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdConsommationRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/consommation'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdDonneesIndexRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/donnees/index'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdDonneesDatasheetNameRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/donnees/$datasheetName'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdDonneesIntegrationRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/donnees/integration'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdDonneesTeleversementRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/donnees/televersement'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdPermissionsIndexRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/permissions/index'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdPermissionsAjoutRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/permissions/ajout'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdPyramideRasterAjoutRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/pyramide-raster/ajout'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdPyramideVecteurAjoutRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/pyramide-vecteur/ajout'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdDonneesStoredDataIdDetailsRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/donnees/$storedDataId.details'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdLivraisonsUploadIdRapportRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/livraisons/$uploadId.rapport'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdPermissionsPermissionIdModificationRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/permissions/$permissionId.modification'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdVisualisationRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/visualisation'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdServiceTmsAjoutRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/service/tms/ajout'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdServiceWfsAjoutRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/service/wfs/ajout'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsRasterAjoutRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/service/wms-raster/ajout'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsVecteurAjoutRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/service/wms-vecteur/ajout'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdServiceWmtsAjoutRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/service/wmts/ajout'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdStyleAjoutRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/style/ajout'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdServiceTmsOfferingIdModificationRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/service/tms/$offeringId.modification'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdServiceWfsOfferingIdModificationRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/service/wfs/$offeringId.modification'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsRasterOfferingIdModificationRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/service/wms-raster/$offeringId.modification'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsVecteurOfferingIdModificationRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/service/wms-vecteur/$offeringId.modification'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdServiceWmtsOfferingIdModificationRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/service/wmts/$offeringId.modification'
import { Route as PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdStyleStyleTechnicalNameModificationRouteImport } from './routes/_private/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/style/$styleTechnicalName.modification'

const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateEspaceCollaboratifRouteRoute =
  PrivateEspaceCollaboratifRouteRouteImport.update({
    id: '/espace-collaboratif',
    path: '/espace-collaboratif',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateMesDocumentsRoute = PrivateMesDocumentsRouteImport.update({
  id: '/mes-documents',
  path: '/mes-documents',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateMesPermissionsRoute = PrivateMesPermissionsRouteImport.update({
  id: '/mes-permissions',
  path: '/mes-permissions',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateMonCompteRoute = PrivateMonCompteRouteImport.update({
  id: '/mon-compte',
  path: '/mon-compte',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateRejoindreDesCommunautesRoute =
  PrivateRejoindreDesCommunautesRouteImport.update({
    id: '/rejoindre-des-communautes',
    path: '/rejoindre-des-communautes',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const Public404Route = Public404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicConnexionDesactiveeRoute =
  PublicConnexionDesactiveeRouteImport.update({
    id: '/connexion-desactivee',
    path: '/connexion-desactivee',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicPublierUneDonneeRoute = PublicPublierUneDonneeRouteImport.update({
  id: '/publier-une-donnee',
  path: '/publier-une-donnee',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivateConfigurationAlertesRoute =
  PrivateConfigurationAlertesRouteImport.update({
    id: '/configuration/alertes',
    path: '/configuration/alertes',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateDemandeAccesFileIdentifierRoute =
  PrivateDemandeAccesFileIdentifierRouteImport.update({
    id: '/demande-acces/$fileIdentifier',
    path: '/demande-acces/$fileIdentifier',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateEspaceCollaboratifIndexRoute =
  PrivateEspaceCollaboratifIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateEspaceCollaboratifRouteRoute,
  } as any)
const PrivateMesClesIndexRoute = PrivateMesClesIndexRouteImport.update({
  id: '/mes-cles/',
  path: '/mes-cles/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateMesClesAjoutRoute = PrivateMesClesAjoutRouteImport.update({
  id: '/mes-cles/ajout',
  path: '/mes-cles/ajout',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateTableauDeBordIndexRoute =
  PrivateTableauDeBordIndexRouteImport.update({
    id: '/tableau-de-bord/',
    path: '/tableau-de-bord/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateTableauDeBordStatistiquesDeConsommationRoute =
  PrivateTableauDeBordStatistiquesDeConsommationRouteImport.update({
    id: '/tableau-de-bord/statistiques-de-consommation',
    path: '/tableau-de-bord/statistiques-de-consommation',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateEspaceCollaboratifCommunityIdCreerUnGuichetRoute =
  PrivateEspaceCollaboratifCommunityIdCreerUnGuichetRouteImport.update({
    id: '/$communityId/creer-un-guichet',
    path: '/$communityId/creer-un-guichet',
    getParentRoute: () => PrivateEspaceCollaboratifRouteRoute,
  } as any)
const PrivateEspaceCollaboratifCommunityIdGererLeGuichetRoute =
  PrivateEspaceCollaboratifCommunityIdGererLeGuichetRouteImport.update({
    id: '/$communityId/gerer-le-guichet',
    path: '/$communityId/gerer-le-guichet',
    getParentRoute: () => PrivateEspaceCollaboratifRouteRoute,
  } as any)
const PrivateEspaceCollaboratifCommunityIdInvitationRoute =
  PrivateEspaceCollaboratifCommunityIdInvitationRouteImport.update({
    id: '/$communityId/invitation',
    path: '/$communityId/invitation',
    getParentRoute: () => PrivateEspaceCollaboratifRouteRoute,
  } as any)
const PrivateMesClesKeyIdModificationRoute =
  PrivateMesClesKeyIdModificationRouteImport.update({
    id: '/mes-cles/$keyId/modification',
    path: '/mes-cles/$keyId/modification',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateTableauDeBordCommunauteCommunityIdRouteRoute =
  PrivateTableauDeBordCommunauteCommunityIdRouteRouteImport.update({
    id: '/tableau-de-bord/communaute/$communityId',
    path: '/tableau-de-bord/communaute/$communityId',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateTableauDeBordEntrepotsIndexRoute =
  PrivateTableauDeBordEntrepotsIndexRouteImport.update({
    id: '/tableau-de-bord/entrepots/',
    path: '/tableau-de-bord/entrepots/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdRouteRouteImport.update({
    id: '/tableau-de-bord/entrepots/$datastoreId',
    path: '/tableau-de-bord/entrepots/$datastoreId',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateTableauDeBordEntrepotsDemandeDeCreationRoute =
  PrivateTableauDeBordEntrepotsDemandeDeCreationRouteImport.update({
    id: '/tableau-de-bord/entrepots/demande-de-creation',
    path: '/tableau-de-bord/entrepots/demande-de-creation',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateTableauDeBordCommunauteCommunityIdIndexRoute =
  PrivateTableauDeBordCommunauteCommunityIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateTableauDeBordCommunauteCommunityIdRouteRoute,
  } as any)
const PrivateTableauDeBordCommunauteCommunityIdMembresRoute =
  PrivateTableauDeBordCommunauteCommunityIdMembresRouteImport.update({
    id: '/membres',
    path: '/membres',
    getParentRoute: () => PrivateTableauDeBordCommunauteCommunityIdRouteRoute,
  } as any)
const PrivateTableauDeBordEntrepotsDatastoreIdConsommationRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdConsommationRouteImport.update({
    id: '/consommation',
    path: '/consommation',
    getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
  } as any)
const PrivateTableauDeBordEntrepotsDatastoreIdDonneesIndexRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdDonneesIndexRouteImport.update({
    id: '/donnees/',
    path: '/donnees/',
    getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
  } as any)
const PrivateTableauDeBordEntrepotsDatastoreIdDonneesDatasheetNameRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdDonneesDatasheetNameRouteImport.update(
    {
      id: '/donnees/$datasheetName',
      path: '/donnees/$datasheetName',
      getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
    } as any,
  )
const PrivateTableauDeBordEntrepotsDatastoreIdDonneesIntegrationRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdDonneesIntegrationRouteImport.update({
    id: '/donnees/integration',
    path: '/donnees/integration',
    getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
  } as any)
const PrivateTableauDeBordEntrepotsDatastoreIdDonneesTeleversementRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdDonneesTeleversementRouteImport.update(
    {
      id: '/donnees/televersement',
      path: '/donnees/televersement',
      getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
    } as any,
  )
const PrivateTableauDeBordEntrepotsDatastoreIdPermissionsIndexRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdPermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
  } as any)
const PrivateTableauDeBordEntrepotsDatastoreIdPermissionsAjoutRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdPermissionsAjoutRouteImport.update({
    id: '/permissions/ajout',
    path: '/permissions/ajout',
    getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
  } as any)
const PrivateTableauDeBordEntrepotsDatastoreIdPyramideRasterAjoutRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdPyramideRasterAjoutRouteImport.update(
    {
      id: '/pyramide-raster/ajout',
      path: '/pyramide-raster/ajout',
      getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
    } as any,
  )
const PrivateTableauDeBordEntrepotsDatastoreIdPyramideVecteurAjoutRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdPyramideVecteurAjoutRouteImport.update(
    {
      id: '/pyramide-vecteur/ajout',
      path: '/pyramide-vecteur/ajout',
      getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
    } as any,
  )
const PrivateTableauDeBordEntrepotsDatastoreIdDonneesStoredDataIdDetailsRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdDonneesStoredDataIdDetailsRouteImport.update(
    {
      id: '/donnees/$storedDataId/details',
      path: '/donnees/$storedDataId/details',
      getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
    } as any,
  )
const PrivateTableauDeBordEntrepotsDatastoreIdLivraisonsUploadIdRapportRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdLivraisonsUploadIdRapportRouteImport.update(
    {
      id: '/livraisons/$uploadId/rapport',
      path: '/livraisons/$uploadId/rapport',
      getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
    } as any,
  )
const PrivateTableauDeBordEntrepotsDatastoreIdPermissionsPermissionIdModificationRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdPermissionsPermissionIdModificationRouteImport.update(
    {
      id: '/permissions/$permissionId/modification',
      path: '/permissions/$permissionId/modification',
      getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
    } as any,
  )
const PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdVisualisationRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdVisualisationRouteImport.update(
    {
      id: '/service/$offeringId/visualisation',
      path: '/service/$offeringId/visualisation',
      getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
    } as any,
  )
const PrivateTableauDeBordEntrepotsDatastoreIdServiceTmsAjoutRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdServiceTmsAjoutRouteImport.update({
    id: '/service/tms/ajout',
    path: '/service/tms/ajout',
    getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
  } as any)
const PrivateTableauDeBordEntrepotsDatastoreIdServiceWfsAjoutRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdServiceWfsAjoutRouteImport.update({
    id: '/service/wfs/ajout',
    path: '/service/wfs/ajout',
    getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
  } as any)
const PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsRasterAjoutRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsRasterAjoutRouteImport.update(
    {
      id: '/service/wms-raster/ajout',
      path: '/service/wms-raster/ajout',
      getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
    } as any,
  )
const PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsVecteurAjoutRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsVecteurAjoutRouteImport.update(
    {
      id: '/service/wms-vecteur/ajout',
      path: '/service/wms-vecteur/ajout',
      getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
    } as any,
  )
const PrivateTableauDeBordEntrepotsDatastoreIdServiceWmtsAjoutRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdServiceWmtsAjoutRouteImport.update({
    id: '/service/wmts/ajout',
    path: '/service/wmts/ajout',
    getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
  } as any)
const PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdStyleAjoutRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdStyleAjoutRouteImport.update(
    {
      id: '/service/$offeringId/style/ajout',
      path: '/service/$offeringId/style/ajout',
      getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
    } as any,
  )
const PrivateTableauDeBordEntrepotsDatastoreIdServiceTmsOfferingIdModificationRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdServiceTmsOfferingIdModificationRouteImport.update(
    {
      id: '/service/tms/$offeringId/modification',
      path: '/service/tms/$offeringId/modification',
      getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
    } as any,
  )
const PrivateTableauDeBordEntrepotsDatastoreIdServiceWfsOfferingIdModificationRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdServiceWfsOfferingIdModificationRouteImport.update(
    {
      id: '/service/wfs/$offeringId/modification',
      path: '/service/wfs/$offeringId/modification',
      getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
    } as any,
  )
const PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsRasterOfferingIdModificationRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsRasterOfferingIdModificationRouteImport.update(
    {
      id: '/service/wms-raster/$offeringId/modification',
      path: '/service/wms-raster/$offeringId/modification',
      getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
    } as any,
  )
const PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsVecteurOfferingIdModificationRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsVecteurOfferingIdModificationRouteImport.update(
    {
      id: '/service/wms-vecteur/$offeringId/modification',
      path: '/service/wms-vecteur/$offeringId/modification',
      getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
    } as any,
  )
const PrivateTableauDeBordEntrepotsDatastoreIdServiceWmtsOfferingIdModificationRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdServiceWmtsOfferingIdModificationRouteImport.update(
    {
      id: '/service/wmts/$offeringId/modification',
      path: '/service/wmts/$offeringId/modification',
      getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
    } as any,
  )
const PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdStyleStyleTechnicalNameModificationRoute =
  PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdStyleStyleTechnicalNameModificationRouteImport.update(
    {
      id: '/service/$offeringId/style/$styleTechnicalName/modification',
      path: '/service/$offeringId/style/$styleTechnicalName/modification',
      getParentRoute: () => PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof PublicRouteRouteWithChildren
  '/espace-collaboratif': typeof PrivateEspaceCollaboratifRouteRouteWithChildren
  '/mes-documents': typeof PrivateMesDocumentsRoute
  '/mes-permissions': typeof PrivateMesPermissionsRoute
  '/mon-compte': typeof PrivateMonCompteRoute
  '/rejoindre-des-communautes': typeof PrivateRejoindreDesCommunautesRoute
  '/404': typeof Public404Route
  '/connexion-desactivee': typeof PublicConnexionDesactiveeRoute
  '/publier-une-donnee': typeof PublicPublierUneDonneeRoute
  '/configuration/alertes': typeof PrivateConfigurationAlertesRoute
  '/demande-acces/$fileIdentifier': typeof PrivateDemandeAccesFileIdentifierRoute
  '/mes-cles/ajout': typeof PrivateMesClesAjoutRoute
  '/tableau-de-bord/statistiques-de-consommation': typeof PrivateTableauDeBordStatistiquesDeConsommationRoute
  '/espace-collaboratif/': typeof PrivateEspaceCollaboratifIndexRoute
  '/mes-cles/': typeof PrivateMesClesIndexRoute
  '/tableau-de-bord/': typeof PrivateTableauDeBordIndexRoute
  '/tableau-de-bord/communaute/$communityId': typeof PrivateTableauDeBordCommunauteCommunityIdRouteRouteWithChildren
  '/tableau-de-bord/entrepots/$datastoreId': typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRouteWithChildren
  '/espace-collaboratif/$communityId/creer-un-guichet': typeof PrivateEspaceCollaboratifCommunityIdCreerUnGuichetRoute
  '/espace-collaboratif/$communityId/gerer-le-guichet': typeof PrivateEspaceCollaboratifCommunityIdGererLeGuichetRoute
  '/espace-collaboratif/$communityId/invitation': typeof PrivateEspaceCollaboratifCommunityIdInvitationRoute
  '/mes-cles/$keyId/modification': typeof PrivateMesClesKeyIdModificationRoute
  '/tableau-de-bord/entrepots/demande-de-creation': typeof PrivateTableauDeBordEntrepotsDemandeDeCreationRoute
  '/tableau-de-bord/entrepots/': typeof PrivateTableauDeBordEntrepotsIndexRoute
  '/tableau-de-bord/communaute/$communityId/membres': typeof PrivateTableauDeBordCommunauteCommunityIdMembresRoute
  '/tableau-de-bord/entrepots/$datastoreId/consommation': typeof PrivateTableauDeBordEntrepotsDatastoreIdConsommationRoute
  '/tableau-de-bord/communaute/$communityId/': typeof PrivateTableauDeBordCommunauteCommunityIdIndexRoute
  '/tableau-de-bord/entrepots/$datastoreId/donnees/$datasheetName': typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesDatasheetNameRoute
  '/tableau-de-bord/entrepots/$datastoreId/donnees/integration': typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesIntegrationRoute
  '/tableau-de-bord/entrepots/$datastoreId/donnees/televersement': typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesTeleversementRoute
  '/tableau-de-bord/entrepots/$datastoreId/permissions/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdPermissionsAjoutRoute
  '/tableau-de-bord/entrepots/$datastoreId/pyramide-raster/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdPyramideRasterAjoutRoute
  '/tableau-de-bord/entrepots/$datastoreId/pyramide-vecteur/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdPyramideVecteurAjoutRoute
  '/tableau-de-bord/entrepots/$datastoreId/donnees/': typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesIndexRoute
  '/tableau-de-bord/entrepots/$datastoreId/permissions/': typeof PrivateTableauDeBordEntrepotsDatastoreIdPermissionsIndexRoute
  '/tableau-de-bord/entrepots/$datastoreId/donnees/$storedDataId/details': typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesStoredDataIdDetailsRoute
  '/tableau-de-bord/entrepots/$datastoreId/livraisons/$uploadId/rapport': typeof PrivateTableauDeBordEntrepotsDatastoreIdLivraisonsUploadIdRapportRoute
  '/tableau-de-bord/entrepots/$datastoreId/permissions/$permissionId/modification': typeof PrivateTableauDeBordEntrepotsDatastoreIdPermissionsPermissionIdModificationRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/visualisation': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdVisualisationRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/tms/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceTmsAjoutRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/wfs/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWfsAjoutRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/wms-raster/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsRasterAjoutRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/wms-vecteur/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsVecteurAjoutRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/wmts/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmtsAjoutRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/style/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdStyleAjoutRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/tms/$offeringId/modification': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceTmsOfferingIdModificationRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/wfs/$offeringId/modification': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWfsOfferingIdModificationRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/wms-raster/$offeringId/modification': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsRasterOfferingIdModificationRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/wms-vecteur/$offeringId/modification': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsVecteurOfferingIdModificationRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/wmts/$offeringId/modification': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmtsOfferingIdModificationRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/style/$styleTechnicalName/modification': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdStyleStyleTechnicalNameModificationRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicRouteRouteWithChildren
  '/mes-documents': typeof PrivateMesDocumentsRoute
  '/mes-permissions': typeof PrivateMesPermissionsRoute
  '/mon-compte': typeof PrivateMonCompteRoute
  '/rejoindre-des-communautes': typeof PrivateRejoindreDesCommunautesRoute
  '/404': typeof Public404Route
  '/connexion-desactivee': typeof PublicConnexionDesactiveeRoute
  '/publier-une-donnee': typeof PublicPublierUneDonneeRoute
  '/configuration/alertes': typeof PrivateConfigurationAlertesRoute
  '/demande-acces/$fileIdentifier': typeof PrivateDemandeAccesFileIdentifierRoute
  '/mes-cles/ajout': typeof PrivateMesClesAjoutRoute
  '/tableau-de-bord/statistiques-de-consommation': typeof PrivateTableauDeBordStatistiquesDeConsommationRoute
  '/espace-collaboratif': typeof PrivateEspaceCollaboratifIndexRoute
  '/mes-cles': typeof PrivateMesClesIndexRoute
  '/tableau-de-bord': typeof PrivateTableauDeBordIndexRoute
  '/tableau-de-bord/entrepots/$datastoreId': typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRouteWithChildren
  '/espace-collaboratif/$communityId/creer-un-guichet': typeof PrivateEspaceCollaboratifCommunityIdCreerUnGuichetRoute
  '/espace-collaboratif/$communityId/gerer-le-guichet': typeof PrivateEspaceCollaboratifCommunityIdGererLeGuichetRoute
  '/espace-collaboratif/$communityId/invitation': typeof PrivateEspaceCollaboratifCommunityIdInvitationRoute
  '/mes-cles/$keyId/modification': typeof PrivateMesClesKeyIdModificationRoute
  '/tableau-de-bord/entrepots/demande-de-creation': typeof PrivateTableauDeBordEntrepotsDemandeDeCreationRoute
  '/tableau-de-bord/entrepots': typeof PrivateTableauDeBordEntrepotsIndexRoute
  '/tableau-de-bord/communaute/$communityId/membres': typeof PrivateTableauDeBordCommunauteCommunityIdMembresRoute
  '/tableau-de-bord/entrepots/$datastoreId/consommation': typeof PrivateTableauDeBordEntrepotsDatastoreIdConsommationRoute
  '/tableau-de-bord/communaute/$communityId': typeof PrivateTableauDeBordCommunauteCommunityIdIndexRoute
  '/tableau-de-bord/entrepots/$datastoreId/donnees/$datasheetName': typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesDatasheetNameRoute
  '/tableau-de-bord/entrepots/$datastoreId/donnees/integration': typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesIntegrationRoute
  '/tableau-de-bord/entrepots/$datastoreId/donnees/televersement': typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesTeleversementRoute
  '/tableau-de-bord/entrepots/$datastoreId/permissions/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdPermissionsAjoutRoute
  '/tableau-de-bord/entrepots/$datastoreId/pyramide-raster/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdPyramideRasterAjoutRoute
  '/tableau-de-bord/entrepots/$datastoreId/pyramide-vecteur/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdPyramideVecteurAjoutRoute
  '/tableau-de-bord/entrepots/$datastoreId/donnees': typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesIndexRoute
  '/tableau-de-bord/entrepots/$datastoreId/permissions': typeof PrivateTableauDeBordEntrepotsDatastoreIdPermissionsIndexRoute
  '/tableau-de-bord/entrepots/$datastoreId/donnees/$storedDataId/details': typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesStoredDataIdDetailsRoute
  '/tableau-de-bord/entrepots/$datastoreId/livraisons/$uploadId/rapport': typeof PrivateTableauDeBordEntrepotsDatastoreIdLivraisonsUploadIdRapportRoute
  '/tableau-de-bord/entrepots/$datastoreId/permissions/$permissionId/modification': typeof PrivateTableauDeBordEntrepotsDatastoreIdPermissionsPermissionIdModificationRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/visualisation': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdVisualisationRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/tms/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceTmsAjoutRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/wfs/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWfsAjoutRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/wms-raster/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsRasterAjoutRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/wms-vecteur/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsVecteurAjoutRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/wmts/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmtsAjoutRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/style/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdStyleAjoutRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/tms/$offeringId/modification': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceTmsOfferingIdModificationRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/wfs/$offeringId/modification': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWfsOfferingIdModificationRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/wms-raster/$offeringId/modification': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsRasterOfferingIdModificationRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/wms-vecteur/$offeringId/modification': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsVecteurOfferingIdModificationRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/wmts/$offeringId/modification': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmtsOfferingIdModificationRoute
  '/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/style/$styleTechnicalName/modification': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdStyleStyleTechnicalNameModificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_private/espace-collaboratif': typeof PrivateEspaceCollaboratifRouteRouteWithChildren
  '/_private/mes-documents': typeof PrivateMesDocumentsRoute
  '/_private/mes-permissions': typeof PrivateMesPermissionsRoute
  '/_private/mon-compte': typeof PrivateMonCompteRoute
  '/_private/rejoindre-des-communautes': typeof PrivateRejoindreDesCommunautesRoute
  '/_public/404': typeof Public404Route
  '/_public/connexion-desactivee': typeof PublicConnexionDesactiveeRoute
  '/_public/publier-une-donnee': typeof PublicPublierUneDonneeRoute
  '/_private/configuration/alertes': typeof PrivateConfigurationAlertesRoute
  '/_private/demande-acces/$fileIdentifier': typeof PrivateDemandeAccesFileIdentifierRoute
  '/_private/mes-cles/ajout': typeof PrivateMesClesAjoutRoute
  '/_private/tableau-de-bord/statistiques-de-consommation': typeof PrivateTableauDeBordStatistiquesDeConsommationRoute
  '/_private/espace-collaboratif/': typeof PrivateEspaceCollaboratifIndexRoute
  '/_private/mes-cles/': typeof PrivateMesClesIndexRoute
  '/_private/tableau-de-bord/': typeof PrivateTableauDeBordIndexRoute
  '/_private/tableau-de-bord/communaute/$communityId': typeof PrivateTableauDeBordCommunauteCommunityIdRouteRouteWithChildren
  '/_private/tableau-de-bord/entrepots/$datastoreId': typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRouteWithChildren
  '/_private/espace-collaboratif/$communityId/creer-un-guichet': typeof PrivateEspaceCollaboratifCommunityIdCreerUnGuichetRoute
  '/_private/espace-collaboratif/$communityId/gerer-le-guichet': typeof PrivateEspaceCollaboratifCommunityIdGererLeGuichetRoute
  '/_private/espace-collaboratif/$communityId/invitation': typeof PrivateEspaceCollaboratifCommunityIdInvitationRoute
  '/_private/mes-cles/$keyId/modification': typeof PrivateMesClesKeyIdModificationRoute
  '/_private/tableau-de-bord/entrepots/demande-de-creation': typeof PrivateTableauDeBordEntrepotsDemandeDeCreationRoute
  '/_private/tableau-de-bord/entrepots/': typeof PrivateTableauDeBordEntrepotsIndexRoute
  '/_private/tableau-de-bord/communaute/$communityId/membres': typeof PrivateTableauDeBordCommunauteCommunityIdMembresRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/consommation': typeof PrivateTableauDeBordEntrepotsDatastoreIdConsommationRoute
  '/_private/tableau-de-bord/communaute/$communityId/': typeof PrivateTableauDeBordCommunauteCommunityIdIndexRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/donnees/$datasheetName': typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesDatasheetNameRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/donnees/integration': typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesIntegrationRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/donnees/televersement': typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesTeleversementRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/permissions/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdPermissionsAjoutRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/pyramide-raster/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdPyramideRasterAjoutRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/pyramide-vecteur/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdPyramideVecteurAjoutRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/donnees/': typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesIndexRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/permissions/': typeof PrivateTableauDeBordEntrepotsDatastoreIdPermissionsIndexRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/donnees/$storedDataId/details': typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesStoredDataIdDetailsRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/livraisons/$uploadId/rapport': typeof PrivateTableauDeBordEntrepotsDatastoreIdLivraisonsUploadIdRapportRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/permissions/$permissionId/modification': typeof PrivateTableauDeBordEntrepotsDatastoreIdPermissionsPermissionIdModificationRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/visualisation': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdVisualisationRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/service/tms/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceTmsAjoutRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/service/wfs/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWfsAjoutRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/service/wms-raster/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsRasterAjoutRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/service/wms-vecteur/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsVecteurAjoutRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/service/wmts/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmtsAjoutRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/style/ajout': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdStyleAjoutRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/service/tms/$offeringId/modification': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceTmsOfferingIdModificationRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/service/wfs/$offeringId/modification': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWfsOfferingIdModificationRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/service/wms-raster/$offeringId/modification': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsRasterOfferingIdModificationRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/service/wms-vecteur/$offeringId/modification': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsVecteurOfferingIdModificationRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/service/wmts/$offeringId/modification': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmtsOfferingIdModificationRoute
  '/_private/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/style/$styleTechnicalName/modification': typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdStyleStyleTechnicalNameModificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/espace-collaboratif'
    | '/mes-documents'
    | '/mes-permissions'
    | '/mon-compte'
    | '/rejoindre-des-communautes'
    | '/404'
    | '/connexion-desactivee'
    | '/publier-une-donnee'
    | '/configuration/alertes'
    | '/demande-acces/$fileIdentifier'
    | '/mes-cles/ajout'
    | '/tableau-de-bord/statistiques-de-consommation'
    | '/espace-collaboratif/'
    | '/mes-cles/'
    | '/tableau-de-bord/'
    | '/tableau-de-bord/communaute/$communityId'
    | '/tableau-de-bord/entrepots/$datastoreId'
    | '/espace-collaboratif/$communityId/creer-un-guichet'
    | '/espace-collaboratif/$communityId/gerer-le-guichet'
    | '/espace-collaboratif/$communityId/invitation'
    | '/mes-cles/$keyId/modification'
    | '/tableau-de-bord/entrepots/demande-de-creation'
    | '/tableau-de-bord/entrepots/'
    | '/tableau-de-bord/communaute/$communityId/membres'
    | '/tableau-de-bord/entrepots/$datastoreId/consommation'
    | '/tableau-de-bord/communaute/$communityId/'
    | '/tableau-de-bord/entrepots/$datastoreId/donnees/$datasheetName'
    | '/tableau-de-bord/entrepots/$datastoreId/donnees/integration'
    | '/tableau-de-bord/entrepots/$datastoreId/donnees/televersement'
    | '/tableau-de-bord/entrepots/$datastoreId/permissions/ajout'
    | '/tableau-de-bord/entrepots/$datastoreId/pyramide-raster/ajout'
    | '/tableau-de-bord/entrepots/$datastoreId/pyramide-vecteur/ajout'
    | '/tableau-de-bord/entrepots/$datastoreId/donnees/'
    | '/tableau-de-bord/entrepots/$datastoreId/permissions/'
    | '/tableau-de-bord/entrepots/$datastoreId/donnees/$storedDataId/details'
    | '/tableau-de-bord/entrepots/$datastoreId/livraisons/$uploadId/rapport'
    | '/tableau-de-bord/entrepots/$datastoreId/permissions/$permissionId/modification'
    | '/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/visualisation'
    | '/tableau-de-bord/entrepots/$datastoreId/service/tms/ajout'
    | '/tableau-de-bord/entrepots/$datastoreId/service/wfs/ajout'
    | '/tableau-de-bord/entrepots/$datastoreId/service/wms-raster/ajout'
    | '/tableau-de-bord/entrepots/$datastoreId/service/wms-vecteur/ajout'
    | '/tableau-de-bord/entrepots/$datastoreId/service/wmts/ajout'
    | '/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/style/ajout'
    | '/tableau-de-bord/entrepots/$datastoreId/service/tms/$offeringId/modification'
    | '/tableau-de-bord/entrepots/$datastoreId/service/wfs/$offeringId/modification'
    | '/tableau-de-bord/entrepots/$datastoreId/service/wms-raster/$offeringId/modification'
    | '/tableau-de-bord/entrepots/$datastoreId/service/wms-vecteur/$offeringId/modification'
    | '/tableau-de-bord/entrepots/$datastoreId/service/wmts/$offeringId/modification'
    | '/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/style/$styleTechnicalName/modification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mes-documents'
    | '/mes-permissions'
    | '/mon-compte'
    | '/rejoindre-des-communautes'
    | '/404'
    | '/connexion-desactivee'
    | '/publier-une-donnee'
    | '/configuration/alertes'
    | '/demande-acces/$fileIdentifier'
    | '/mes-cles/ajout'
    | '/tableau-de-bord/statistiques-de-consommation'
    | '/espace-collaboratif'
    | '/mes-cles'
    | '/tableau-de-bord'
    | '/tableau-de-bord/entrepots/$datastoreId'
    | '/espace-collaboratif/$communityId/creer-un-guichet'
    | '/espace-collaboratif/$communityId/gerer-le-guichet'
    | '/espace-collaboratif/$communityId/invitation'
    | '/mes-cles/$keyId/modification'
    | '/tableau-de-bord/entrepots/demande-de-creation'
    | '/tableau-de-bord/entrepots'
    | '/tableau-de-bord/communaute/$communityId/membres'
    | '/tableau-de-bord/entrepots/$datastoreId/consommation'
    | '/tableau-de-bord/communaute/$communityId'
    | '/tableau-de-bord/entrepots/$datastoreId/donnees/$datasheetName'
    | '/tableau-de-bord/entrepots/$datastoreId/donnees/integration'
    | '/tableau-de-bord/entrepots/$datastoreId/donnees/televersement'
    | '/tableau-de-bord/entrepots/$datastoreId/permissions/ajout'
    | '/tableau-de-bord/entrepots/$datastoreId/pyramide-raster/ajout'
    | '/tableau-de-bord/entrepots/$datastoreId/pyramide-vecteur/ajout'
    | '/tableau-de-bord/entrepots/$datastoreId/donnees'
    | '/tableau-de-bord/entrepots/$datastoreId/permissions'
    | '/tableau-de-bord/entrepots/$datastoreId/donnees/$storedDataId/details'
    | '/tableau-de-bord/entrepots/$datastoreId/livraisons/$uploadId/rapport'
    | '/tableau-de-bord/entrepots/$datastoreId/permissions/$permissionId/modification'
    | '/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/visualisation'
    | '/tableau-de-bord/entrepots/$datastoreId/service/tms/ajout'
    | '/tableau-de-bord/entrepots/$datastoreId/service/wfs/ajout'
    | '/tableau-de-bord/entrepots/$datastoreId/service/wms-raster/ajout'
    | '/tableau-de-bord/entrepots/$datastoreId/service/wms-vecteur/ajout'
    | '/tableau-de-bord/entrepots/$datastoreId/service/wmts/ajout'
    | '/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/style/ajout'
    | '/tableau-de-bord/entrepots/$datastoreId/service/tms/$offeringId/modification'
    | '/tableau-de-bord/entrepots/$datastoreId/service/wfs/$offeringId/modification'
    | '/tableau-de-bord/entrepots/$datastoreId/service/wms-raster/$offeringId/modification'
    | '/tableau-de-bord/entrepots/$datastoreId/service/wms-vecteur/$offeringId/modification'
    | '/tableau-de-bord/entrepots/$datastoreId/service/wmts/$offeringId/modification'
    | '/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/style/$styleTechnicalName/modification'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/espace-collaboratif'
    | '/_private/mes-documents'
    | '/_private/mes-permissions'
    | '/_private/mon-compte'
    | '/_private/rejoindre-des-communautes'
    | '/_public/404'
    | '/_public/connexion-desactivee'
    | '/_public/publier-une-donnee'
    | '/_private/configuration/alertes'
    | '/_private/demande-acces/$fileIdentifier'
    | '/_private/mes-cles/ajout'
    | '/_private/tableau-de-bord/statistiques-de-consommation'
    | '/_private/espace-collaboratif/'
    | '/_private/mes-cles/'
    | '/_private/tableau-de-bord/'
    | '/_private/tableau-de-bord/communaute/$communityId'
    | '/_private/tableau-de-bord/entrepots/$datastoreId'
    | '/_private/espace-collaboratif/$communityId/creer-un-guichet'
    | '/_private/espace-collaboratif/$communityId/gerer-le-guichet'
    | '/_private/espace-collaboratif/$communityId/invitation'
    | '/_private/mes-cles/$keyId/modification'
    | '/_private/tableau-de-bord/entrepots/demande-de-creation'
    | '/_private/tableau-de-bord/entrepots/'
    | '/_private/tableau-de-bord/communaute/$communityId/membres'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/consommation'
    | '/_private/tableau-de-bord/communaute/$communityId/'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/donnees/$datasheetName'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/donnees/integration'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/donnees/televersement'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/permissions/ajout'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/pyramide-raster/ajout'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/pyramide-vecteur/ajout'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/donnees/'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/permissions/'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/donnees/$storedDataId/details'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/livraisons/$uploadId/rapport'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/permissions/$permissionId/modification'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/visualisation'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/service/tms/ajout'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/service/wfs/ajout'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/service/wms-raster/ajout'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/service/wms-vecteur/ajout'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/service/wmts/ajout'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/style/ajout'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/service/tms/$offeringId/modification'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/service/wfs/$offeringId/modification'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/service/wms-raster/$offeringId/modification'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/service/wms-vecteur/$offeringId/modification'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/service/wmts/$offeringId/modification'
    | '/_private/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/style/$styleTechnicalName/modification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/espace-collaboratif': {
      id: '/_private/espace-collaboratif'
      path: '/espace-collaboratif'
      fullPath: '/espace-collaboratif'
      preLoaderRoute: typeof PrivateEspaceCollaboratifRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/mes-documents': {
      id: '/_private/mes-documents'
      path: '/mes-documents'
      fullPath: '/mes-documents'
      preLoaderRoute: typeof PrivateMesDocumentsRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/mes-permissions': {
      id: '/_private/mes-permissions'
      path: '/mes-permissions'
      fullPath: '/mes-permissions'
      preLoaderRoute: typeof PrivateMesPermissionsRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/mon-compte': {
      id: '/_private/mon-compte'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof PrivateMonCompteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/rejoindre-des-communautes': {
      id: '/_private/rejoindre-des-communautes'
      path: '/rejoindre-des-communautes'
      fullPath: '/rejoindre-des-communautes'
      preLoaderRoute: typeof PrivateRejoindreDesCommunautesRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_public/404': {
      id: '/_public/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof Public404RouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/connexion-desactivee': {
      id: '/_public/connexion-desactivee'
      path: '/connexion-desactivee'
      fullPath: '/connexion-desactivee'
      preLoaderRoute: typeof PublicConnexionDesactiveeRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/publier-une-donnee': {
      id: '/_public/publier-une-donnee'
      path: '/publier-une-donnee'
      fullPath: '/publier-une-donnee'
      preLoaderRoute: typeof PublicPublierUneDonneeRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_private/configuration/alertes': {
      id: '/_private/configuration/alertes'
      path: '/configuration/alertes'
      fullPath: '/configuration/alertes'
      preLoaderRoute: typeof PrivateConfigurationAlertesRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/demande-acces/$fileIdentifier': {
      id: '/_private/demande-acces/$fileIdentifier'
      path: '/demande-acces/$fileIdentifier'
      fullPath: '/demande-acces/$fileIdentifier'
      preLoaderRoute: typeof PrivateDemandeAccesFileIdentifierRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/espace-collaboratif/': {
      id: '/_private/espace-collaboratif/'
      path: '/'
      fullPath: '/espace-collaboratif/'
      preLoaderRoute: typeof PrivateEspaceCollaboratifIndexRouteImport
      parentRoute: typeof PrivateEspaceCollaboratifRouteRoute
    }
    '/_private/mes-cles/': {
      id: '/_private/mes-cles/'
      path: '/mes-cles'
      fullPath: '/mes-cles/'
      preLoaderRoute: typeof PrivateMesClesIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/mes-cles/ajout': {
      id: '/_private/mes-cles/ajout'
      path: '/mes-cles/ajout'
      fullPath: '/mes-cles/ajout'
      preLoaderRoute: typeof PrivateMesClesAjoutRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/tableau-de-bord/': {
      id: '/_private/tableau-de-bord/'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord/'
      preLoaderRoute: typeof PrivateTableauDeBordIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/tableau-de-bord/statistiques-de-consommation': {
      id: '/_private/tableau-de-bord/statistiques-de-consommation'
      path: '/tableau-de-bord/statistiques-de-consommation'
      fullPath: '/tableau-de-bord/statistiques-de-consommation'
      preLoaderRoute: typeof PrivateTableauDeBordStatistiquesDeConsommationRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/espace-collaboratif/$communityId/creer-un-guichet': {
      id: '/_private/espace-collaboratif/$communityId/creer-un-guichet'
      path: '/$communityId/creer-un-guichet'
      fullPath: '/espace-collaboratif/$communityId/creer-un-guichet'
      preLoaderRoute: typeof PrivateEspaceCollaboratifCommunityIdCreerUnGuichetRouteImport
      parentRoute: typeof PrivateEspaceCollaboratifRouteRoute
    }
    '/_private/espace-collaboratif/$communityId/gerer-le-guichet': {
      id: '/_private/espace-collaboratif/$communityId/gerer-le-guichet'
      path: '/$communityId/gerer-le-guichet'
      fullPath: '/espace-collaboratif/$communityId/gerer-le-guichet'
      preLoaderRoute: typeof PrivateEspaceCollaboratifCommunityIdGererLeGuichetRouteImport
      parentRoute: typeof PrivateEspaceCollaboratifRouteRoute
    }
    '/_private/espace-collaboratif/$communityId/invitation': {
      id: '/_private/espace-collaboratif/$communityId/invitation'
      path: '/$communityId/invitation'
      fullPath: '/espace-collaboratif/$communityId/invitation'
      preLoaderRoute: typeof PrivateEspaceCollaboratifCommunityIdInvitationRouteImport
      parentRoute: typeof PrivateEspaceCollaboratifRouteRoute
    }
    '/_private/mes-cles/$keyId/modification': {
      id: '/_private/mes-cles/$keyId/modification'
      path: '/mes-cles/$keyId/modification'
      fullPath: '/mes-cles/$keyId/modification'
      preLoaderRoute: typeof PrivateMesClesKeyIdModificationRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/tableau-de-bord/communaute/$communityId': {
      id: '/_private/tableau-de-bord/communaute/$communityId'
      path: '/tableau-de-bord/communaute/$communityId'
      fullPath: '/tableau-de-bord/communaute/$communityId'
      preLoaderRoute: typeof PrivateTableauDeBordCommunauteCommunityIdRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/': {
      id: '/_private/tableau-de-bord/entrepots/'
      path: '/tableau-de-bord/entrepots'
      fullPath: '/tableau-de-bord/entrepots/'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId'
      path: '/tableau-de-bord/entrepots/$datastoreId'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/demande-de-creation': {
      id: '/_private/tableau-de-bord/entrepots/demande-de-creation'
      path: '/tableau-de-bord/entrepots/demande-de-creation'
      fullPath: '/tableau-de-bord/entrepots/demande-de-creation'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDemandeDeCreationRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/tableau-de-bord/communaute/$communityId/': {
      id: '/_private/tableau-de-bord/communaute/$communityId/'
      path: '/'
      fullPath: '/tableau-de-bord/communaute/$communityId/'
      preLoaderRoute: typeof PrivateTableauDeBordCommunauteCommunityIdIndexRouteImport
      parentRoute: typeof PrivateTableauDeBordCommunauteCommunityIdRouteRoute
    }
    '/_private/tableau-de-bord/communaute/$communityId/membres': {
      id: '/_private/tableau-de-bord/communaute/$communityId/membres'
      path: '/membres'
      fullPath: '/tableau-de-bord/communaute/$communityId/membres'
      preLoaderRoute: typeof PrivateTableauDeBordCommunauteCommunityIdMembresRouteImport
      parentRoute: typeof PrivateTableauDeBordCommunauteCommunityIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/consommation': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/consommation'
      path: '/consommation'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/consommation'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdConsommationRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/donnees/': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/donnees/'
      path: '/donnees'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/donnees/'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesIndexRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/donnees/$datasheetName': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/donnees/$datasheetName'
      path: '/donnees/$datasheetName'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/donnees/$datasheetName'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesDatasheetNameRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/donnees/integration': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/donnees/integration'
      path: '/donnees/integration'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/donnees/integration'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesIntegrationRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/donnees/televersement': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/donnees/televersement'
      path: '/donnees/televersement'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/donnees/televersement'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesTeleversementRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/permissions/': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/permissions/'
      path: '/permissions'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/permissions/'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdPermissionsIndexRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/permissions/ajout': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/permissions/ajout'
      path: '/permissions/ajout'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/permissions/ajout'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdPermissionsAjoutRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/pyramide-raster/ajout': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/pyramide-raster/ajout'
      path: '/pyramide-raster/ajout'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/pyramide-raster/ajout'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdPyramideRasterAjoutRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/pyramide-vecteur/ajout': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/pyramide-vecteur/ajout'
      path: '/pyramide-vecteur/ajout'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/pyramide-vecteur/ajout'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdPyramideVecteurAjoutRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/donnees/$storedDataId/details': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/donnees/$storedDataId/details'
      path: '/donnees/$storedDataId/details'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/donnees/$storedDataId/details'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesStoredDataIdDetailsRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/livraisons/$uploadId/rapport': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/livraisons/$uploadId/rapport'
      path: '/livraisons/$uploadId/rapport'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/livraisons/$uploadId/rapport'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdLivraisonsUploadIdRapportRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/permissions/$permissionId/modification': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/permissions/$permissionId/modification'
      path: '/permissions/$permissionId/modification'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/permissions/$permissionId/modification'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdPermissionsPermissionIdModificationRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/visualisation': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/visualisation'
      path: '/service/$offeringId/visualisation'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/visualisation'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdVisualisationRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/service/tms/ajout': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/service/tms/ajout'
      path: '/service/tms/ajout'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/service/tms/ajout'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceTmsAjoutRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/service/wfs/ajout': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/service/wfs/ajout'
      path: '/service/wfs/ajout'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/service/wfs/ajout'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWfsAjoutRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/service/wms-raster/ajout': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/service/wms-raster/ajout'
      path: '/service/wms-raster/ajout'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/service/wms-raster/ajout'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsRasterAjoutRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/service/wms-vecteur/ajout': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/service/wms-vecteur/ajout'
      path: '/service/wms-vecteur/ajout'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/service/wms-vecteur/ajout'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsVecteurAjoutRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/service/wmts/ajout': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/service/wmts/ajout'
      path: '/service/wmts/ajout'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/service/wmts/ajout'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmtsAjoutRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/style/ajout': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/style/ajout'
      path: '/service/$offeringId/style/ajout'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/style/ajout'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdStyleAjoutRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/service/tms/$offeringId/modification': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/service/tms/$offeringId/modification'
      path: '/service/tms/$offeringId/modification'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/service/tms/$offeringId/modification'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceTmsOfferingIdModificationRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/service/wfs/$offeringId/modification': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/service/wfs/$offeringId/modification'
      path: '/service/wfs/$offeringId/modification'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/service/wfs/$offeringId/modification'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWfsOfferingIdModificationRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/service/wms-raster/$offeringId/modification': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/service/wms-raster/$offeringId/modification'
      path: '/service/wms-raster/$offeringId/modification'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/service/wms-raster/$offeringId/modification'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsRasterOfferingIdModificationRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/service/wms-vecteur/$offeringId/modification': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/service/wms-vecteur/$offeringId/modification'
      path: '/service/wms-vecteur/$offeringId/modification'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/service/wms-vecteur/$offeringId/modification'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsVecteurOfferingIdModificationRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/service/wmts/$offeringId/modification': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/service/wmts/$offeringId/modification'
      path: '/service/wmts/$offeringId/modification'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/service/wmts/$offeringId/modification'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmtsOfferingIdModificationRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
    '/_private/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/style/$styleTechnicalName/modification': {
      id: '/_private/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/style/$styleTechnicalName/modification'
      path: '/service/$offeringId/style/$styleTechnicalName/modification'
      fullPath: '/tableau-de-bord/entrepots/$datastoreId/service/$offeringId/style/$styleTechnicalName/modification'
      preLoaderRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdStyleStyleTechnicalNameModificationRouteImport
      parentRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute
    }
  }
}

interface PrivateEspaceCollaboratifRouteRouteChildren {
  PrivateEspaceCollaboratifIndexRoute: typeof PrivateEspaceCollaboratifIndexRoute
  PrivateEspaceCollaboratifCommunityIdCreerUnGuichetRoute: typeof PrivateEspaceCollaboratifCommunityIdCreerUnGuichetRoute
  PrivateEspaceCollaboratifCommunityIdGererLeGuichetRoute: typeof PrivateEspaceCollaboratifCommunityIdGererLeGuichetRoute
  PrivateEspaceCollaboratifCommunityIdInvitationRoute: typeof PrivateEspaceCollaboratifCommunityIdInvitationRoute
}

const PrivateEspaceCollaboratifRouteRouteChildren: PrivateEspaceCollaboratifRouteRouteChildren =
  {
    PrivateEspaceCollaboratifIndexRoute: PrivateEspaceCollaboratifIndexRoute,
    PrivateEspaceCollaboratifCommunityIdCreerUnGuichetRoute:
      PrivateEspaceCollaboratifCommunityIdCreerUnGuichetRoute,
    PrivateEspaceCollaboratifCommunityIdGererLeGuichetRoute:
      PrivateEspaceCollaboratifCommunityIdGererLeGuichetRoute,
    PrivateEspaceCollaboratifCommunityIdInvitationRoute:
      PrivateEspaceCollaboratifCommunityIdInvitationRoute,
  }

const PrivateEspaceCollaboratifRouteRouteWithChildren =
  PrivateEspaceCollaboratifRouteRoute._addFileChildren(
    PrivateEspaceCollaboratifRouteRouteChildren,
  )

interface PrivateTableauDeBordCommunauteCommunityIdRouteRouteChildren {
  PrivateTableauDeBordCommunauteCommunityIdMembresRoute: typeof PrivateTableauDeBordCommunauteCommunityIdMembresRoute
  PrivateTableauDeBordCommunauteCommunityIdIndexRoute: typeof PrivateTableauDeBordCommunauteCommunityIdIndexRoute
}

const PrivateTableauDeBordCommunauteCommunityIdRouteRouteChildren: PrivateTableauDeBordCommunauteCommunityIdRouteRouteChildren =
  {
    PrivateTableauDeBordCommunauteCommunityIdMembresRoute:
      PrivateTableauDeBordCommunauteCommunityIdMembresRoute,
    PrivateTableauDeBordCommunauteCommunityIdIndexRoute:
      PrivateTableauDeBordCommunauteCommunityIdIndexRoute,
  }

const PrivateTableauDeBordCommunauteCommunityIdRouteRouteWithChildren =
  PrivateTableauDeBordCommunauteCommunityIdRouteRoute._addFileChildren(
    PrivateTableauDeBordCommunauteCommunityIdRouteRouteChildren,
  )

interface PrivateTableauDeBordEntrepotsDatastoreIdRouteRouteChildren {
  PrivateTableauDeBordEntrepotsDatastoreIdConsommationRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdConsommationRoute
  PrivateTableauDeBordEntrepotsDatastoreIdDonneesDatasheetNameRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesDatasheetNameRoute
  PrivateTableauDeBordEntrepotsDatastoreIdDonneesIntegrationRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesIntegrationRoute
  PrivateTableauDeBordEntrepotsDatastoreIdDonneesTeleversementRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesTeleversementRoute
  PrivateTableauDeBordEntrepotsDatastoreIdPermissionsAjoutRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdPermissionsAjoutRoute
  PrivateTableauDeBordEntrepotsDatastoreIdPyramideRasterAjoutRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdPyramideRasterAjoutRoute
  PrivateTableauDeBordEntrepotsDatastoreIdPyramideVecteurAjoutRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdPyramideVecteurAjoutRoute
  PrivateTableauDeBordEntrepotsDatastoreIdDonneesIndexRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesIndexRoute
  PrivateTableauDeBordEntrepotsDatastoreIdPermissionsIndexRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdPermissionsIndexRoute
  PrivateTableauDeBordEntrepotsDatastoreIdDonneesStoredDataIdDetailsRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdDonneesStoredDataIdDetailsRoute
  PrivateTableauDeBordEntrepotsDatastoreIdLivraisonsUploadIdRapportRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdLivraisonsUploadIdRapportRoute
  PrivateTableauDeBordEntrepotsDatastoreIdPermissionsPermissionIdModificationRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdPermissionsPermissionIdModificationRoute
  PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdVisualisationRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdVisualisationRoute
  PrivateTableauDeBordEntrepotsDatastoreIdServiceTmsAjoutRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceTmsAjoutRoute
  PrivateTableauDeBordEntrepotsDatastoreIdServiceWfsAjoutRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWfsAjoutRoute
  PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsRasterAjoutRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsRasterAjoutRoute
  PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsVecteurAjoutRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsVecteurAjoutRoute
  PrivateTableauDeBordEntrepotsDatastoreIdServiceWmtsAjoutRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmtsAjoutRoute
  PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdStyleAjoutRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdStyleAjoutRoute
  PrivateTableauDeBordEntrepotsDatastoreIdServiceTmsOfferingIdModificationRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceTmsOfferingIdModificationRoute
  PrivateTableauDeBordEntrepotsDatastoreIdServiceWfsOfferingIdModificationRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWfsOfferingIdModificationRoute
  PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsRasterOfferingIdModificationRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsRasterOfferingIdModificationRoute
  PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsVecteurOfferingIdModificationRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsVecteurOfferingIdModificationRoute
  PrivateTableauDeBordEntrepotsDatastoreIdServiceWmtsOfferingIdModificationRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceWmtsOfferingIdModificationRoute
  PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdStyleStyleTechnicalNameModificationRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdStyleStyleTechnicalNameModificationRoute
}

const PrivateTableauDeBordEntrepotsDatastoreIdRouteRouteChildren: PrivateTableauDeBordEntrepotsDatastoreIdRouteRouteChildren =
  {
    PrivateTableauDeBordEntrepotsDatastoreIdConsommationRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdConsommationRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdDonneesDatasheetNameRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdDonneesDatasheetNameRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdDonneesIntegrationRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdDonneesIntegrationRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdDonneesTeleversementRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdDonneesTeleversementRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdPermissionsAjoutRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdPermissionsAjoutRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdPyramideRasterAjoutRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdPyramideRasterAjoutRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdPyramideVecteurAjoutRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdPyramideVecteurAjoutRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdDonneesIndexRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdDonneesIndexRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdPermissionsIndexRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdPermissionsIndexRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdDonneesStoredDataIdDetailsRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdDonneesStoredDataIdDetailsRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdLivraisonsUploadIdRapportRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdLivraisonsUploadIdRapportRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdPermissionsPermissionIdModificationRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdPermissionsPermissionIdModificationRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdVisualisationRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdVisualisationRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdServiceTmsAjoutRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdServiceTmsAjoutRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdServiceWfsAjoutRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdServiceWfsAjoutRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsRasterAjoutRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsRasterAjoutRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsVecteurAjoutRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsVecteurAjoutRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdServiceWmtsAjoutRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdServiceWmtsAjoutRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdStyleAjoutRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdStyleAjoutRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdServiceTmsOfferingIdModificationRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdServiceTmsOfferingIdModificationRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdServiceWfsOfferingIdModificationRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdServiceWfsOfferingIdModificationRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsRasterOfferingIdModificationRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsRasterOfferingIdModificationRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsVecteurOfferingIdModificationRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdServiceWmsVecteurOfferingIdModificationRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdServiceWmtsOfferingIdModificationRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdServiceWmtsOfferingIdModificationRoute,
    PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdStyleStyleTechnicalNameModificationRoute:
      PrivateTableauDeBordEntrepotsDatastoreIdServiceOfferingIdStyleStyleTechnicalNameModificationRoute,
  }

const PrivateTableauDeBordEntrepotsDatastoreIdRouteRouteWithChildren =
  PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute._addFileChildren(
    PrivateTableauDeBordEntrepotsDatastoreIdRouteRouteChildren,
  )

interface PrivateRouteRouteChildren {
  PrivateEspaceCollaboratifRouteRoute: typeof PrivateEspaceCollaboratifRouteRouteWithChildren
  PrivateMesDocumentsRoute: typeof PrivateMesDocumentsRoute
  PrivateMesPermissionsRoute: typeof PrivateMesPermissionsRoute
  PrivateMonCompteRoute: typeof PrivateMonCompteRoute
  PrivateRejoindreDesCommunautesRoute: typeof PrivateRejoindreDesCommunautesRoute
  PrivateConfigurationAlertesRoute: typeof PrivateConfigurationAlertesRoute
  PrivateDemandeAccesFileIdentifierRoute: typeof PrivateDemandeAccesFileIdentifierRoute
  PrivateMesClesAjoutRoute: typeof PrivateMesClesAjoutRoute
  PrivateTableauDeBordStatistiquesDeConsommationRoute: typeof PrivateTableauDeBordStatistiquesDeConsommationRoute
  PrivateMesClesIndexRoute: typeof PrivateMesClesIndexRoute
  PrivateTableauDeBordIndexRoute: typeof PrivateTableauDeBordIndexRoute
  PrivateTableauDeBordCommunauteCommunityIdRouteRoute: typeof PrivateTableauDeBordCommunauteCommunityIdRouteRouteWithChildren
  PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute: typeof PrivateTableauDeBordEntrepotsDatastoreIdRouteRouteWithChildren
  PrivateMesClesKeyIdModificationRoute: typeof PrivateMesClesKeyIdModificationRoute
  PrivateTableauDeBordEntrepotsDemandeDeCreationRoute: typeof PrivateTableauDeBordEntrepotsDemandeDeCreationRoute
  PrivateTableauDeBordEntrepotsIndexRoute: typeof PrivateTableauDeBordEntrepotsIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateEspaceCollaboratifRouteRoute:
    PrivateEspaceCollaboratifRouteRouteWithChildren,
  PrivateMesDocumentsRoute: PrivateMesDocumentsRoute,
  PrivateMesPermissionsRoute: PrivateMesPermissionsRoute,
  PrivateMonCompteRoute: PrivateMonCompteRoute,
  PrivateRejoindreDesCommunautesRoute: PrivateRejoindreDesCommunautesRoute,
  PrivateConfigurationAlertesRoute: PrivateConfigurationAlertesRoute,
  PrivateDemandeAccesFileIdentifierRoute:
    PrivateDemandeAccesFileIdentifierRoute,
  PrivateMesClesAjoutRoute: PrivateMesClesAjoutRoute,
  PrivateTableauDeBordStatistiquesDeConsommationRoute:
    PrivateTableauDeBordStatistiquesDeConsommationRoute,
  PrivateMesClesIndexRoute: PrivateMesClesIndexRoute,
  PrivateTableauDeBordIndexRoute: PrivateTableauDeBordIndexRoute,
  PrivateTableauDeBordCommunauteCommunityIdRouteRoute:
    PrivateTableauDeBordCommunauteCommunityIdRouteRouteWithChildren,
  PrivateTableauDeBordEntrepotsDatastoreIdRouteRoute:
    PrivateTableauDeBordEntrepotsDatastoreIdRouteRouteWithChildren,
  PrivateMesClesKeyIdModificationRoute: PrivateMesClesKeyIdModificationRoute,
  PrivateTableauDeBordEntrepotsDemandeDeCreationRoute:
    PrivateTableauDeBordEntrepotsDemandeDeCreationRoute,
  PrivateTableauDeBordEntrepotsIndexRoute:
    PrivateTableauDeBordEntrepotsIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  Public404Route: typeof Public404Route
  PublicConnexionDesactiveeRoute: typeof PublicConnexionDesactiveeRoute
  PublicPublierUneDonneeRoute: typeof PublicPublierUneDonneeRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  Public404Route: Public404Route,
  PublicConnexionDesactiveeRoute: PublicConnexionDesactiveeRoute,
  PublicPublierUneDonneeRoute: PublicPublierUneDonneeRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
