name: Ajouter au projet "Suivi global Cartes.gouv" si label "suivi" est ajouté

on:
    issues:
        types: [opened, labeled]

# Le GITHUB_TOKEN n'est pas utilisé : l'action s'authentifie via ADD_TO_PROJECT_PAT
permissions: {}

jobs:
    add-to-project:
        name: Ajoute au projet
        runs-on: ubuntu-latest
        steps:
            - uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e # v1.0.2
              with:
                  project-url: https://github.com/orgs/IGNF/projects/53
                  github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
                  labeled: suivi
